# Generated by Django 4.2.1 on 2023-06-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_shanghairanking_theranking_webometricsranking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shanghairanking',
            name='ranking',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shanghairanking',
            name='subject',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shanghairanking',
            name='year',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
