# Generated by Django 4.2.1 on 2023-06-16 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_studentfeedback_q1_studentfeedback_q2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
