# Generated by Django 4.2.1 on 2023-06-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_shanghairanking_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shanghairanking',
            name='year',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
