# Generated by Django 4.2.1 on 2023-06-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_ranking_delete_shanghairanking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QSRanking',
        ),
        migrations.DeleteModel(
            name='THERanking',
        ),
        migrations.DeleteModel(
            name='WebometricsRanking',
        ),
    ]
