# Generated by Django 4.2.1 on 2023-06-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_delete_qsranking_delete_theranking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, null=True)),
                ('year', models.CharField(max_length=200, null=True)),
                ('ranking', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shanghai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, null=True)),
                ('year', models.CharField(max_length=200, null=True)),
                ('ranking', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='THE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, null=True)),
                ('year', models.CharField(max_length=200, null=True)),
                ('ranking', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Webometrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, null=True)),
                ('year', models.CharField(max_length=200, null=True)),
                ('ranking', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Ranking',
        ),
    ]
